const { createCanvas } = require('canvas');
const countryService = require('./countryService');
const fs = require('fs');
const path = require('path');

class ImageService {
  constructor() {
    this.cacheDir = path.join(__dirname, '../cache');
    this.ensureCacheDir();
  }

  ensureCacheDir() {
    if (!fs.existsSync(this.cacheDir)) {
      fs.mkdirSync(this.cacheDir, { recursive: true });
    }
  }

  async generateSummaryImage() {
    try {
      const topCountries = await countryService.getTopCountriesByGDP(5);
      const status = await countryService.getStatus();

      // Create canvas
      const canvas = createCanvas(800, 600);
      const ctx = canvas.getContext('2d');

      // Background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, 800, 600);

      // Title
      ctx.fillStyle = '#2c3e50';
      ctx.font = 'bold 32px Arial';
      ctx.textAlign = 'center';
      ctx.fillText('Countries Summary Report', 400, 60);

      // Total countries
      ctx.font = 'bold 20px Arial';
      ctx.textAlign = 'left';
      ctx.fillText(`Total Countries: ${status.total_countries}`, 50, 120);

      // Last refresh
      ctx.fillText(`Last Refresh: ${new Date(status.last_refreshed_at).toLocaleString()}`, 50, 160);

      // Top countries title
      ctx.font = 'bold 24px Arial';
      ctx.fillText('Top 5 Countries by Estimated GDP:', 50, 220);

      // Top countries list
      ctx.font = '18px Arial';
      let yPosition = 260;
      
      ctx.fillStyle = '#34495e';
      topCountries.forEach((country, index) => {
        const gdpFormatted = new Intl.NumberFormat('en-US', {
          style: 'currency',
          currency: 'USD',
          minimumFractionDigits: 2,
          maximumFractionDigits: 2
        }).format(country.estimated_gdp / 1e9); // Convert to billions
        
        ctx.fillText(
          `${index + 1}. ${country.name}: ${gdpFormatted}B`,
          70,
          yPosition
        );
        yPosition += 35;
      });

      // Footer
      ctx.fillStyle = '#7f8c8d';
      ctx.font = '14px Arial';
      ctx.textAlign = 'center';
      ctx.fillText('Generated by Country Currency API', 400, 580);

      // Save image to cache directory
      const buffer = canvas.toBuffer('image/png');
      const imagePath = path.join(this.cacheDir, 'summary.png');
      fs.writeFileSync(imagePath, buffer);

      console.log('Summary image generated successfully');
      return imagePath;
    } catch (error) {
      console.error('Image generation error:', error);
      throw error;
    }
  }

  getImagePath() {
    const imagePath = path.join(this.cacheDir, 'summary.png');
    return fs.existsSync(imagePath) ? imagePath : null;
  }
}

module.exports = new ImageService();